# Prod profile configuration

# Database Configuration for Postgres
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging:
  level:
    org.springframework: INFO

# Server Configuration
server:
  port: 8082
